compilar: ej3.c funciones.c funciones.h
	gcc ej3.c funciones.c -o ej3_estudio.exe

ejecutar-ascendente: ej3_estudio.exe binario.txt
	./ej3_estudio.exe 1 binario.txt 

ejecutar-descendente: ej3_estudio.exe binario.txt
	./ej3_estudio.exe 2 binario.txt

